#if 0
//
// Generated by 2.0.21076.0
//
//   fxc /Fh opengl.ps.replace_modulate.h /Tps_3_0 opengl.hlsl
//    /Eps_replace_modulate
//
//
// Parameters:
//
//   sampler2D texture0;
//   sampler2D texture1;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   texture0     s0       1
//   texture1     s1       1
//

// Shader type: pixel 

xps_3_0
defconst texture0, sampler2d, object, [1, 1], s0
defconst texture1, sampler2d, object, [1, 1], s1
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=2
// PsExportColorCount=1
// PsSampleControl=both

dcl_texcoord r0.xy
dcl_texcoord1 r1.xy
dcl_color_centroid r2


    exec
    tfetch2D r2, r0.xy, tf0
    tfetch2D r0, r1.xy, tf1
    alloc colors
    exece
    mul oC0, r2, r0

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_ps_replace_modulate[] =
{
    0x102a1100, 0x000000d0, 0x00000048, 0x00000000, 0x00000024, 0x00000000, 
    0x000000a4, 0x00000000, 0x00000000, 0x0000007c, 0x0000001c, 0x00000070, 
    0xffff0300, 0x00000002, 0x0000001c, 0x00000000, 0x00000069, 0x00000044, 
    0x00030000, 0x00010000, 0x00000050, 0x00000000, 0x00000060, 0x00030001, 
    0x00010000, 0x00000050, 0x00000000, 0x74657874, 0x75726530, 0x00ababab, 
    0x0004000c, 0x00010001, 0x00010000, 0x00000000, 0x74657874, 0x75726531, 
    0x0070735f, 0x335f3000, 0x322e302e, 0x32313037, 0x362e3000, 0x00000000, 
    0x00000048, 0x10000200, 0x00000008, 0x00000000, 0x00002063, 0x00030007, 
    0x00000001, 0x00003050, 0x00003151, 0x0000f2a0, 0x00052002, 0x00001200, 
    0xc4000000, 0x00001004, 0x00002200, 0x00000000, 0x10082001, 0x1f1ff688, 
    0x00004000, 0x10180021, 0x1f1ff688, 0x00004000, 0xc80f8000, 0x00000000, 
    0xe1020000, 0x00000000, 0x00000000, 0x00000000
};
