#if 0
//
// Generated by 2.0.21076.0
//
//   fxc /Fh opengl.vs.h /Tvs_3_0 opengl.hlsl /Evs_main
//
//
// Parameters:
//
//   float4x4 modelview_matrix;
//   float4x4 projection_matrix;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   modelview_matrix  c0       4
//   projection_matrix c8       4
//

// Shader type: vertex 

xvs_3_0
defconst modelview_matrix, float, matrix_columns, [4, 4], c0-3
defconst projection_matrix, float, matrix_columns, [4, 4], c8-11
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=12
config VsResource=1
// VsExportCount=2

dcl_index r0.x
dcl_texcoord o0.xy
dcl_texcoord1 o1.xy
dcl_color o2


    exec
    vfetch r2, r0.x, position
    vfetch r1.__xy, r0.x, texcoord
    vfetch r1.xy__, r0.x, texcoord1
    vfetch r0, r0.x, color
    alloc position
    exec
    mul r6, c11.wxzy, c1.w
    mul r10, c11.xwzy, c2.w
    mul r7, c10.xwzy, c3.z
    mul r5, c10.xwzy, c1.z
    mul r4, c10.xwzy, c0.z
    mul r3, c10.xwzy, c2.z
    exec
    mad r3, c9.xzyw, c2.y, r3.xzwy
    mad r4, c9.xzyw, c0.y, r4.xzwy
    mad r5, c9.xzyw, c1.y, r5.xzwy
    mad r7, c9.xzyw, c3.y, r7.xzwy
    mad r8, c8.xywz, c3.x, r7.xzwy
    mad r9, c8.xywz, c1.x, r5.xzwy
    exec
    mad r12, c8.xywz, c0.x, r4.xzwy
    mad r11, c8.xywz, c2.x, r3.xzwy
    mul r5, c11.wzxy, c0.w
  + movs r0._, r11.z
    add r3.x, r12.z, r5.x
  + adds_prev r3.z, r10.y
    mul r7, c11.xwzy, c3.w
  + movs r0._, r9.z
    add r3.w, r8.z, r7.y
  + adds_prev r3.y, r6.x
    exec
    add r4.y, r9.w, r6.z
  + movs r0._, r12.w
    add r4.z, r11.w, r10.z
  + adds_prev r4.x, r5.y
    add r5.x, r12.y, r5.w
  + movs r0._, r8.w
    add r5.y, r9.y, r6.w
  + adds_prev r4.w, r7.z
    add r5.w, r8.y, r7.w
  + movs r0._, r11.y
    add r6.x, r12.x, r5.z
  + adds_prev r5.z, r10.w
    exec
    add r6.z, r11.x, r10.x
  + movs r0._, r9.x
    add r6.w, r8.x, r7.x
  + adds_prev r6.y, r6.y
    dp4 oPos.x, r6.wzxy, r2.wzxy
    dp4 oPos.y, r5.wzxy, r2.wzxy
    dp4 oPos.z, r4.wzxy, r2.wzxy
    dp4 oPos.w, r3.wzxy, r2.wzxy
    alloc interpolators
    exece
    mov o0.xy, r1.zw
    mov o1.xy, r1.xy
    mov o2, r0

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xvs_vs_main[] =
{
    0x102a1101, 0x00000108, 0x00000204, 0x00000000, 0x00000024, 0x00000000, 
    0x000000b8, 0x00000000, 0x00000000, 0x00000090, 0x0000001c, 0x00000081, 
    0xfffe0300, 0x00000002, 0x0000001c, 0x00000000, 0x0000007a, 0x00000044, 
    0x00020000, 0x00040000, 0x00000058, 0x00000000, 0x00000068, 0x00020008, 
    0x00040000, 0x00000058, 0x00000000, 0x6d6f6465, 0x6c766965, 0x775f6d61, 
    0x74726978, 0x00ababab, 0x00030003, 0x00040004, 0x00010000, 0x00000000, 
    0x70726f6a, 0x65637469, 0x6f6e5f6d, 0x61747269, 0x78007673, 0x5f335f30, 
    0x00322e30, 0x2e323130, 0x37362e30, 0x00ababab, 0x00000000, 0x00000204, 
    0x0021000c, 0x00000000, 0x00000000, 0x00002063, 0x00000001, 0x00000004, 
    0x00000003, 0x00000290, 0x00100005, 0x00005006, 0x00015007, 0x0030a008, 
    0x00003050, 0x00013151, 0x0002f2a0, 0x00001027, 0x00001028, 0x00001029, 
    0xf0554005, 0x00001200, 0xc2000000, 0x00006009, 0x600f1200, 0x12000000, 
    0x00006015, 0x601b1200, 0x12000000, 0x00006021, 0x00001200, 0xc4000000, 
    0x00003027, 0x00002200, 0x00000000, 0x05f82000, 0x00000688, 0x00000000, 
    0x05f81000, 0x0000023f, 0x00000000, 0x05f81000, 0x00000fc8, 0x00000000, 
    0x05f80000, 0x00000688, 0x00000000, 0xc80f0006, 0x008f1b00, 0x210b0100, 
    0xc80f000a, 0x00881b00, 0x210b0200, 0xc80f0007, 0x0088c600, 0x210a0300, 
    0xc80f0005, 0x0088c600, 0x210a0100, 0xc80f0004, 0x0088c600, 0x210a0000, 
    0xc80f0003, 0x0088c600, 0x210a0200, 0xc80f0003, 0x0034b194, 0x2b090203, 
    0xc80f0004, 0x0034b194, 0x2b090004, 0xc80f0005, 0x0034b194, 0x2b090105, 
    0xc80f0007, 0x0034b194, 0x2b090307, 0xc80f0008, 0x00d06c94, 0x2b080307, 
    0xc80f0009, 0x00d06c94, 0x2b080105, 0xc80f000c, 0x00d06c94, 0x2b080004, 
    0xc80f000b, 0x00d06c94, 0x2b080203, 0x140f0005, 0x00a71bc6, 0x210b000b, 
    0x04410303, 0x00c66cb1, 0xe00c050a, 0x140f0007, 0x00881bc6, 0x210b0309, 
    0x04280303, 0x00c6b16c, 0xe0080706, 0x14020004, 0x001bc61b, 0xe009060c, 
    0x04140404, 0x001bc6b1, 0xe00b0a05, 0x14010005, 0x00b11b1b, 0xe00c0508, 
    0x04820405, 0x00b11bc6, 0xe0090607, 0x14080005, 0x00b11bb1, 0xe008070b, 
    0x04410506, 0x006cc61b, 0xe00c050a, 0x14040006, 0x006c6c6c, 0xe00b0a09, 
    0x04280606, 0x006c6cb1, 0xe0080706, 0xc801803e, 0x00a7a700, 0xef060200, 
    0xc802803e, 0x00a7a700, 0xef050200, 0xc804803e, 0x00a7a700, 0xef040200, 
    0xc808803e, 0x00a7a700, 0xef030200, 0xc8038000, 0x001a1a00, 0xe2010100, 
    0xc8038001, 0x00b0b000, 0xe2010100, 0xc80f8002, 0x00000000, 0xe2000000, 
    0x00000000, 0x00000000, 0x00000000
};
