#if 0
//
// Generated by 2.0.21076.0
//
//   fxc /Fh opengl.vs.post_process.h /Tvs_3_0 opengl.hlsl /Epost_process_main
//
// Shader type: vertex 

xvs_3_0
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=2
config VsResource=1
// VsExportCount=2

dcl_index r0.x
dcl_texcoord o0.xy
dcl_texcoord1 o1.xy
dcl_color o2


    exec
    vfetch r2, r0.x, position
    vfetch r1.__xy, r0.x, texcoord
    vfetch r1.xy__, r0.x, texcoord1
    vfetch r0, r0.x, color
    alloc position
    exec
    mov oPos, r2
    alloc interpolators
    exece
    mov o0.xy, r1.zw
    mov o1.xy, r1.xy
    mov o2, r0

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xvs_post_process_main[] =
{
    0x102a1101, 0x000000a8, 0x00000090, 0x00000000, 0x00000024, 0x00000000, 
    0x00000058, 0x00000000, 0x00000000, 0x00000030, 0x0000001c, 0x00000023, 
    0xfffe0300, 0x00000000, 0x00000000, 0x00000000, 0x0000001c, 0x76735f33, 
    0x5f300032, 0x2e302e32, 0x31303736, 0x2e3000ab, 0x00000000, 0x00000090, 
    0x00210002, 0x00000000, 0x00000000, 0x00002063, 0x00000001, 0x00000004, 
    0x00000003, 0x00000290, 0x00100003, 0x00005004, 0x00015005, 0x0030a006, 
    0x00003050, 0x00013151, 0x0002f2a0, 0x00001008, 0x00001009, 0x0000100a, 
    0xf0554003, 0x00001200, 0xc2000000, 0x00001007, 0x00001200, 0xc4000000, 
    0x00003008, 0x00002200, 0x00000000, 0x05f82000, 0x00000688, 0x00000000, 
    0x05f81000, 0x0000023f, 0x00000000, 0x05f81000, 0x00000fc8, 0x00000000, 
    0x05f80000, 0x00000688, 0x00000000, 0xc80f803e, 0x00000000, 0xe2020200, 
    0xc8038000, 0x001a1a00, 0xe2010100, 0xc8038001, 0x00b0b000, 0xe2010100, 
    0xc80f8002, 0x00000000, 0xe2000000, 0x00000000, 0x00000000, 0x00000000
};
